fieldLayouts:
  13fa4895-3189-43ea-b1e6-c7cb0455920e:
    tabs:
      -
        elements:
          -
            instructions: null
            label: ''
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 533f0b92-38fe-4773-be1b-1da4054b7c4e
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 'Tab 1'
        sortOrder: 1
handle: about
hasTitleField: false
name: About
section: ee26dc2d-cec8-48e9-a3c9-555dcdbcf509
sortOrder: 1
titleFormat: '{section.name|raw}'
