contentColumnType: text
fieldGroup: 8a13fe14-3631-4781-8dfb-fcdcf59d35c9
handle: homepageHobbiesSubtitle
instructions: ''
name: 'Homepage Hobbies Subtitle'
searchable: true
settings:
  charLimit: ''
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
