contentColumnType: text
fieldGroup: 2270990d-10df-4e07-9c5a-7b8cfa1b0000
handle: languages
instructions: 'Languages used at job'
name: Languages
searchable: true
settings:
  columnType: text
  purifierConfig: ''
  purifyHtml: '1'
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
