contentColumnType: text
fieldGroup: 2270990d-10df-4e07-9c5a-7b8cfa1b0000
handle: tools
instructions: 'Tools I used in job'
name: Tools
searchable: true
settings:
  columnType: text
  purifierConfig: ''
  purifyHtml: '1'
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
